### ISSUE TITLE
Bolsanaro 

### ISSUE THREAD

**Issue by nsrce** [nsrce/TheGreatTranslationMovement#1]
![image](https://user-images.githubusercontent.com/100821325/156495730-1a9a5f73-8fd9-448c-a1f2-58cc7e5cdda6.png)

**Comment by chonglang3344** [comment]
Have you noticed, other than the few lapdog countries, most of the Asian countries are quiet, in reality other than the west, most other countries are quiet. The only reason why the world is condemning Russia is because the west has a strong media propaganda.

The west so called world wide condemnation is only a USA and their lapdogs

Destroy the western media, its disgusting

Europe and USA's "whole world" is only 800 million people

**Comment by nsrce** [comment]
![Bolsanaro #1](https://user-images.githubusercontent.com/100821325/156888200-22da2f95-2e08-4f4b-9994-fbbbb48bb31d.png)
