### ISSUE TITLE
从国家利益考虑

### ISSUE THREAD

**Issue by nsrce** [nsrce/TheGreatTranslationMovement#12]
![image](https://user-images.githubusercontent.com/100821325/156505008-c8d85834-5bb8-43da-9573-cf776821a53e.png)

**Comment by teikokusyoujyo** [comment]
'on be half of China, no matter if Russia support us or not, it is beneficial for us to support Russia to win the war against Ukraine from a geological perspective in order to reduce the pressure the West had put upon China.'

'lmao what? youre saying they are the reason that you are unable to pay your child's tuition fees? or unable to pay your medical insurance? or unable to pay your loans?' (most liked)

'so the West is also the cause of infertility? (rofl)'

**Comment by TonTanTin** [comment]
![New Microsoft PowerPoint Presentation](https://user-images.githubusercontent.com/66287884/156510412-890de700-79db-4e41-a52b-3465a720dadd.jpg)
