### ISSUE TITLE
就算俄罗斯把乌克兰人全杀了

### ISSUE THREAD

**Issue by nsrce** [nsrce/TheGreatTranslationMovement#15]
![image](https://user-images.githubusercontent.com/100821325/156510681-725979c3-9389-4422-9837-8431bf30bc1e.png)

**Comment by Carefour** [comment]
1. Even if Russia murdered everyone in Ukraine, woman and children included, I will support Russia. Our enemy is the West and anything that hurt them is our advantage. 
2. It is ok, we will support anything russia do. 
3. We need a strong ally to destroy America. Destroying America is a drawn out battle.  
4. Before we destroy America, Russia is our back to back ally. 
5. Why we feel proud and elated when we hear the national anthem of Russia?

**Comment by Carefour** [comment]
4. 那一个 Back to back 有更贴切的翻译吗？

**Comment by o0o20xxo0o** [comment]
heart to heart?

**Comment by teikokusyoujyo** [comment]
我看看

**Comment by teikokusyoujyo** [comment]
1. We would support Russia even if Russia committed a massacre that killed all Ukrainian people and kids (just like the japanese massacare) because our biggest enemy is the USA and the Europeans. Everything they dislike of is worthy of support. Hope there was another 911.
2. dw bro with our press constantly acknowledging Russia we would support them no matter what
3. it is crucial for us to have a strong ally to destroy USA and win the battle.
4. until the USA colllapses, Russia will always be our best ally.
5. we feel proud when we hear Russia's national anthem!

**Comment by nsrce** [comment]
> 1. We would support Russia even if Russia committed a massacre that killed all Ukrainian people and kids (just like the japanese massacare) because our biggest enemy is the USA and the Europeans. Everything they dislike of is worthy of support. Hope there was another 911.
> 2. dw bro with our press constantly acknowledging Russia we would support them no matter what
> 3. it is crucial for us to have a strong ally to destroy USA and win the battle.
> 4. until the USA colllapses, Russia will always be our best ally.
> 5. we feel proud when we hear Russia's national anthem!

This is not complete as the picture product has not been produced

**Comment by kkklienian** [comment]
<img width="693" alt="Screen Shot 2022-03-03 at 3 58 33 PM" src="https://user-images.githubusercontent.com/100822387/156521582-9675eb76-4b2c-4e91-9c77-94b2f6aac38d.png">
