### ISSUE TITLE
俄羅斯人應該得諾貝爾和平獎

### ISSUE THREAD

**Issue by kkklienian** [nsrce/TheGreatTranslationMovement#26]
![image](https://user-images.githubusercontent.com/100822387/156553268-43de50d2-83ec-4841-b7f5-04c62c217671.png)

**Comment by teikokusyoujyo** [comment]
white American pigs has to be eliminated in order to achieve peace.

Those fucking american pigs are always the ones behind all the conflicts that has happened.

They are either straight up dumbasses or has sexual perversions; or looking like an ugly shortass with their genes inherited from their ancestors; or they are crazy.

In order to prevent people getting rabies, some of the lunatic dogs needs to be killed! 
with the same logic, in order to prevent war, white american pigs needs to be killed.

The Russian soldiers are fighting for peace for the humanity, they fucking deserve a Nobel Peace Prize! (flowers)(flowers)(flowers)

**Comment by kkklienian** [comment]
<img width="646" alt="Screen Shot 2022-03-03 at 10 24 07 PM" src="https://user-images.githubusercontent.com/100822387/156583872-d8aff944-1c41-4464-9876-44da5f624eb0.png">
