### ISSUE TITLE
俄罗斯官兵死亡

### ISSUE THREAD

**Issue by o0o20xxo0o** [nsrce/TheGreatTranslationMovement#34]
![RDT_20220305_130401817179727644189863](https://user-images.githubusercontent.com/92959884/156868890-70066b3b-88d0-482f-820b-c23af8a3681f.jpg)
![RDT_20220305_1304487569999174037578640](https://user-images.githubusercontent.com/92959884/156868899-37a5c952-d9e3-49b2-a41f-07eb47537e0a.jpg)
![RDT_20220305_130453821929404898981989](https://user-images.githubusercontent.com/92959884/156868905-0d3cea54-8310-4f92-acfa-165a5f2c6b3f.jpg)
![RDT_20220305_1304042060738357294245411](https://user-images.githubusercontent.com/92959884/156868908-9a445b52-62f4-43e7-8086-3564a302953f.jpg)

**Comment by chonglang3344** [comment]
News Article: 
Andrei Sukhovetsky, Russian general killed in Ukraine-Russia conflict

Comments:
Salute! Russian General that still have integrity to fight on the front lines, he is a real hero!

Respect to the American Resistance Hero.
Respect to the American Resistance Hero.
Salute to the Hero.

Its commendable to sacrifice oneself for a just cause, Salute to the Hero

A man with responsibility ❤️ 

Ukrainians can you see this? his sacrifice was done to reduce your civilian casualties.

Respect to the Warrior Race (Russians are considered a race of warriors in China), I pray that Russia will return victorious quickly.

A General that died in line of duty, Salute to the Hero.

**Comment by chonglang3344** [comment]
F#ck, this is such a pity. This person is at the level of a successor (To Putin). "A clay pot next to a well will eventually be break, Its unavoidable for a general in constant battles to die in combat." (This is a famous Chinese poem), he died in battle for his country his death was not in vain.
TN NOTE: The poem choice is interesting because it can also used to describe when a person does bad things it will eventually catch up to them :)

Pay respect to the Hero! Salute the warrior race! (Russians)

Salute! ура (Russian battle cry)

Pray for the war to stop and world peace.

The sniper/sharpshooter is really good

To die in battle is honorable for a soldier, salute!

Salute to the hero, the Russian people will remember you forever!

**Comment by chonglang3344** [comment]
Salute to the hero, glory to Russia

Salute to the hero

My respect to all the Russian warriors for their sacrifice.

Use the Soviet tactics, large scale mobilization to penetrate deeply, cut the enemies supply, be merciless.

If it wasn't for the civilians there wouldn't be so many Russian casualties
- Yes the Russians are performing admirably in this regard.

**Comment by chonglang3344** [comment]
![俄罗斯官兵死亡 #3_1](https://user-images.githubusercontent.com/100935706/156926741-6a18ef7b-7fe5-4ff8-90e0-a765a2f1f13d.png)
![俄罗斯官兵死亡 #3_2](https://user-images.githubusercontent.com/100935706/156926742-466b9939-e96e-419e-bc0c-9edc039fc3ce.png)
